// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCghewGy4Hkn80IqpoABrCyCF-PFqBBuB4',
    appId: '1:1017789483064:web:4fd2630edea3a34b19becd',
    messagingSenderId: '1017789483064',
    projectId: 'semproject-5bfca',
    authDomain: 'semproject-5bfca.firebaseapp.com',
    storageBucket: 'semproject-5bfca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSHYMlG12PWtLKOBZFXzx6_N7nmPIyNQY',
    appId: '1:1017789483064:android:0d84fb5bc64b337f19becd',
    messagingSenderId: '1017789483064',
    projectId: 'semproject-5bfca',
    storageBucket: 'semproject-5bfca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG3dwwnr59q_lMbEZbdYUJL84yGmRjsU4',
    appId: '1:1017789483064:ios:146abdb5377555ca19becd',
    messagingSenderId: '1017789483064',
    projectId: 'semproject-5bfca',
    storageBucket: 'semproject-5bfca.firebasestorage.app',
    iosBundleId: 'com.example.flutterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG3dwwnr59q_lMbEZbdYUJL84yGmRjsU4',
    appId: '1:1017789483064:ios:146abdb5377555ca19becd',
    messagingSenderId: '1017789483064',
    projectId: 'semproject-5bfca',
    storageBucket: 'semproject-5bfca.firebasestorage.app',
    iosBundleId: 'com.example.flutterproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCghewGy4Hkn80IqpoABrCyCF-PFqBBuB4',
    appId: '1:1017789483064:web:2ca67115610cc67d19becd',
    messagingSenderId: '1017789483064',
    projectId: 'semproject-5bfca',
    authDomain: 'semproject-5bfca.firebaseapp.com',
    storageBucket: 'semproject-5bfca.firebasestorage.app',
  );
}
